config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :categories
  #resources :orders
  get "/orders", to: "orders#index", as: "orders"
  post "/orders", to: "orders#index", as: "sort_orders"
  get "/orders/new", to: "orders#new", as: "new_order"
  post "/orders/new", to: "orders#create", as: "create_order"
  get "/orders/edit/:id", to: "orders#edit", as: "edit_order"
  patch "/orders/edit/:id", to: "orders#update", as: "update_order"
  post "/orders/:id", to: "orders#destroy", as: "destroy_order"
  
  resources :executors
  resources :services
  root "orders#index"
end

app/models/service.rb
class Service < ApplicationRecord
    belongs_to :category
    has_many :order_services, dependent: :destroy
    has_many :orders, through: :order_services

    validates :name, presence: true
    validates :cost, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :find_category, only: [:edit, :update, :destroy]
    before_action :fetch_categories, only: [:new, :edit]
    
    def index
        @services = Service.all.order(category_id: :asc, name: :asc)
    end

    def new
        @service = Service.new
    end

    def create
        @service = Service.new(service_params)
        if @service.save
            redirect_back(fallback_location: root_path)
            flash[:success] = "Услуга добавлена!"
        else
            redirect_back(fallback_location: root_path)
            flash[:warning] = "Услуга не добавлена!"
        end
    end

    def edit
    end

    def update
        if @service.update service_params
            redirect_to(services_path)
            flash[:success] = "Услуга изменена"
        else
            redirect_to(request.referrer || root_path)
            flash[:warning] = "Не удалось изменить услугу"
        end    
    end

    def destroy
        @service.destroy
        redirect_to(services_path)
        flash[:success] = "Услуга удалена"
    end

    private
    def service_params
        params.require(:service).permit(:name, :category_id, :cost)
    end

    def find_category
        @service = Service.find params[:id]  
    end

    def fetch_categories
        @categories = Category.all
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with model: @service do |service|%>
    <div class="mb-3 row mt-3">
        <%= service.label :name, 'Название', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
            <%= service.text_field :name, class: 'form-control' %>
        </div>
    </div>
    <div class="mb-3 row mt-3">
        <%= service.label :cost, 'Цена', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
            <%= service.text_field :cost, class: 'form-control' %>
        </div>
    </div>
    <div class="mb-3 row mt-3">
        <%= service.label :category, 'Выбор категории', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
            <%= service.collection_select :category_id, @categories, :id, :name, {}, { :size => 3 } %>
        </div>
    </div>
    <%= service.submit "Отправить", class: 'btn btn-primary'%>
<% end %>

app/views/services/edit.html.erb
<h1>Редактирование услуги</h1>
<%= render "form"%>

app/views/services/index.html.erb
<div class="row">
    <div class="col-6 col-sm-2 text-left">
        <h2>Услуга</h2>  
    </div>
    <div class="col-6 col-sm-2 text-left">
        <h2>Цена</h2>  
    </div>
    <div class="col-6 col-sm-2 text-left">
        <h2>Категория</h2>  
    </div>
</div>
<% @services.each do |service|%>
    <hr>
    <div class="row">
        <div class="col-6 col-sm-2 text-left">
            <%= service.name %>
        </div>
        <div class="col-6 col-sm-2 text-left">
            <%= service.cost %>
        </div>          
        <div class="col-6 col-sm-2 text-left">
            <%= service.category.name %>
        </div>
        <div class="col-6">
        <%= link_to "Редактировать", edit_service_path(service.id), class: "btn btn-secondary" %>
        <%= link_to "Удалить", service_path(service), data: {turbo_method: :delete, turbo_confirm: "Вы уверены?"}, class: "btn btn-danger" %>
        </div>
    </div>
<% end %>
<hr>
<div>
    <%= link_to "Добавить услугу", new_service_path, class: "btn btn-primary" %>
</div>

app/views/services/new.html.erb
<h1>Добавление услуги</h1>
<%= render "form"%>