config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :categories
  #resources :orders
  get "/orders", to: "orders#index", as: "orders"
  post "/orders", to: "orders#index", as: "sort_orders"
  get "/orders/new", to: "orders#new", as: "new_order"
  post "/orders/new", to: "orders#create", as: "create_order"
  get "/orders/edit/:id", to: "orders#edit", as: "edit_order"
  patch "/orders/edit/:id", to: "orders#update", as: "update_order"
  post "/orders/:id", to: "orders#destroy", as: "destroy_order"
  
  resources :executors
  resources :services
  root "orders#index"
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :executor
    has_many :order_services, dependent: :destroy
    has_many :services, through: :order_services

    validates :cost, presence: true

    scope :created_filter, ->(time) { where("created_at = ?", time) if time.present? }

    def calc_cost_create
        self.cost = calc_cost(self.services)
    end

    def calc_cost_update
        cost = calc_cost(self.services)
        self.update(:cost => cost)
    end

    def calc_cost(services)
        cost = 0
        services.each{
            |id| service = Service.find_by id: id
            cost += service.cost
        }
        return cost
    end

    def format_created_at
        self.created_at.strftime('%H:%M:%S %d-%m-%Y') 
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :fetch_services, only: [:new, :edit, :index]
    before_action :fetch_executors, only: [:new, :edit, :index]
    before_action :fetch_categories, only: [:index]
    before_action :find_order, only: [:edit, :update, :destroy]

    

    def index 
        if request.get?
            
            respond_to do |format|
                format.html {@orders = Order.all}
                format.xlsx {respond_xlsx()}
            end    
        elsif request.post?
            @orders = filter()
            @orders = sort(@orders)
            session[:orders] = @orders
            respond_to do |format| 
               format.turbo_stream 
            end    
        end
    end

    def new
        @order = Order.new
    end

    def create
        @order = Order.new(order_params)
        @order.calc_cost_create
        if @order.save
            redirect_to(orders_path)
            flash[:success] = "Заказ успешно создан!"
        else
            redirect_to(orders_path)
            flash[:warning] = "Заказ не был создан!"
        end
    end
    
    def edit
        respond_to do |format| 
            format.html
            format.turbo_stream 
        end 
    end

    def update
        OrderService.where("order_id = #{@order.id}").destroy_all
        if @order.update order_params
            @order.calc_cost_update
            redirect_to(orders_path)
            flash[:success] = "Заказ успешно изменен!"
        else
            redirect_to(orders_path)
            flash[:warning] = "Заказ не был изменен!"
        end
    end

    def destroy
        OrderService.where("order_id = #{@order.id}").destroy_all
        @order.destroy
        respond_to do |format|
            format.html{
                redirect_to(orders_path)
                flash[:success] = "Заказ удален"
            }
            format.turbo_stream
        end    
    end

    private

    def order_params
        params.require(:order).permit(:executor_id, service_ids:[])
    end

    def fetch_services
        @services = Service.all.order(name: :asc)
    end

    def fetch_executors
        @executors = Executor.all.order(second_name: :asc)
    end

    def fetch_categories
        @categories = Category.all.order(name: :asc)
    end

    def find_order
        @order = Order.find params[:id]  
    end

    def fetch_filters
        filt_serv = []
        if params[:service][:service_ids].length != 1
            params[:service].each{|key, value| filt_serv.append(value)}
        else
            Service.select(:id).all.each{|value| filt_serv.append(value)}
        end
        filt_categ = []
        if params[:category][:category_ids].length != 1
            params[:category].each{|key, value| filt_categ.append(value)}
        else
            Category.select(:id).all.each{|value| filt_categ.append(value)}
        end
        filt_exe = []
        if params[:executor][:executor_ids].length != 1
            params[:executor].each{|key, value| filt_exe.append(value)}
        else
            Executor.select(:id).all.each{|value| filt_exe.append(value)}
        end
        return [filt_serv, filt_categ, filt_exe]
    end

    def filter
        filters = fetch_filters()

            @orders = Order.all.where(:executor_id => filters[2])
            .where(:id => OrderService.select(:order_id)
                .where(:service_id => Service.select(:id)
                    .where(:id => filters[0])
                    .where(:category_id => Category.select(:id)
                        .where(:id => filters[1])
                    )
                )
            )
            if params[:created_at] != "" 
                @orders = @orders.all.where("'#{params[:created_at]} 00:00:00' < created_at ").where("'#{params[:created_at]} 23:59:59' > created_at")
            else     
                return @orders 
            end
    end

    def sort(orders)
        if params[:cost_sort] != "" && params[:date_sort] != ""
            orders.order(cost: :"#{params[:cost_sort]}").order(created_at: :"#{params[:date_sort]}")
        elsif params[:cost_sort] != "" 
            orders.order(cost: :"#{params[:cost_sort]}")
        elsif params[:date_sort] != ""
            orders.order(created_at: :"#{params[:date_sort]}")
        else
            orders
        end
        # Согласен, странно написан метод, но удивительно то, что иначе он не работает
        # А может я не совсем понимаю, как работает экземпляр @orders и плохо пишу код
    end

    def respond_xlsx()
        @orders = Array.new
        @executors = Array.new
        @services = Array.new
        @categories = Array.new
        session[:orders].each{|order| 
            order = Order.find_by id: order["id"]
            @orders.append(order)
            @executors.append(order.executor)
            tmp_s = order.services
            tmp_c = Array.new
            tmp_s.each{|service| 
                order.services.each{|service| tmp_c.append(service.category)}
            }
            @services.append(tmp_s)
            @categories.append(tmp_c)
        }
        xlsx_doc = render_to_string(
                            layout: false, handlers: [:axlsx], formats: [:xlsx],
                            template: "orders/index",
                            locals: {orders: @orders, 
                                executors: @executors,
                                services: @services,
                                categories: @categories
                            }
                        )               
        send_data xlsx_doc, filename: "orders_table_#{Time.now}.xls"
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_filters.html.erb
    <article class="card mb-3"> 
        <%= form_with url: sort_orders_path do |f|%>
            <section class="card-header">
                <div class="row text-center">
                    <h2>Фильтры</h2>
                </div>
                <div class="row text-center">
                    <div class="col">Услуги</div>
                    <div class="col">Категории услуг</div>
                    <div class="col">Исполнители</div>
                    <div class="col">Дата</div>
                </div>
            </section>
            <section class="card-body">
                <div class="row text-center">
                    <div class="col"> 
                        <%= select("service", "service_ids", services.all.collect {|p| [ p.name, p.id ] }, { include_blank: false }, { :multiple => true, :size => 3 }) %>
                    </div>
                    <div class="col">
                        <%= select("category", "category_ids", categories.all.collect {|p| [ p.name, p.id ] }, { include_blank: false }, { :multiple => true, :size => 3 }) %>
                    </div>
                    <div class="col">
                        <%= select("executor", "executor_ids", executors.all.collect {|p| [ p.second_name, p.id ] }, { include_blank: false }, { :multiple => true, :size => 3 }) %>
                    </div>
                    <div class="col">
                        <input type="date" name="created_at" id="created_at">
                    </div>
                </div>
                <hr>
                <div class="row text-center mt-3">
                    <div class="col-sm-2 my-4">
                        Сортировка:
                    </div>
                    <div class="col-sm-2">
                        Цена <%= f.select :cost_sort, [["Нет", nil], ['По убыванию', "desc"], ['По возрастанию', "asc"]], size:3 %>
                    </div>
                    <div class="col-sm-2">
                        Дата <%= f.select :date_sort, [["Нет", nil], ['По убыванию', "desc"], ['По возрастанию', "asc"]], size:3 %>
                    </div>
                </div>
            </section>
            <section class="card-footer">
                
                    <%= button_to "Применить", sort_orders_path, class: "btn btn-primary" %>
                    <%= link_to "Экспортировать заказы в excel", sort_orders_path(format: :xlsx), class: "btn btn-primary" %>
                    <%= $filter_orders %>
                       
            </section>
        <% end %>
    </article>
  

app/views/orders/_form.html.erb
<%= form_with model: @order, url: url do |order|%>
    <div class="row">  
        <div class="mb-3 row mt-3">
            <%= order.label :name, 'Выбор услуг', class: 'col-sm-2 col-form-label' %>
            <div class="col-sm-10">
                <%= order.collection_select :service_ids, @services, :id, :name, {}, multiple: true, size: 3 %>
            </div>
        </div>
    </div>

    <div class="mb-3 row mt-3">
        <%= order.label :name, 'Выбор Исполнителя', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
            <%= order.collection_select :executor_id, @executors, :id, :second_name, {}, size: 3 %>
        </div>
    </div>
    <%= order.submit "Добавить", class: 'btn btn-primary'%>
<% end %>

app/views/orders/_orders.html.erb
<% orders.each do |order|%>
    <%=turbo_frame_tag order.id do%>
        <article class="card mb-3 mt-3">
            <section class="card-header">
                <div class="row">
                    <div class="col-6 col-sm text-center">
                        Номер заказа 
                    </div>
                    <div class="col-6 col-sm text-center">
                        Услуги 
                    </div>
                    <div class="col-6 col-sm text-center">
                        Исполнитель  
                    </div>
                    <div class="col-6 col-sm text-center">
                        Денежная сумма
                    </div>
                    <div class="col-6 col-sm text-center">
                        Дата создания  
                    </div>
                </div>
            </section>
            <section class="card-body">
                <div class="row ">
                    <div class="col-6 col-sm text-center">
                        <%= order.id %>
                    </div>
                    <div class="col-6 col-sm text-center">
                        <% order.services.each do |s| %>
                            (<%= s.name %>)
                        <% end %>
                    </div>
                    <div class="col-6 col-sm text-center">
                        <%= order.executor.name %>
                        <%= order.executor.second_name %>
                    </div>
                    <div class="col-6 col-sm text-center">
                        <%= order.cost%>
                    </div>
                    <div class="col-6 col-sm text-center">
                        <time datetime="<%= order.format_created_at %>">
                            <%= order.format_created_at %>
                        </time>
                    </div>
                </div>
            </section> 
            <section class="card-footer">
                <div class="row">
                    <div class="col-sm-1">
                        <%= link_to "Редактировать", edit_order_path(order.id), class: "btn btn-secondary", data: {turbo_frame: order.id}%>
                    </div>    
                    <div class="col-sm-2 mx-5">
                        <%= button_to "Удалить", destroy_order_path(order.id), class: "btn btn-danger", data: {turbo_frame: order.id, turbo_method: :destroy}%>
                    </div>
                </div>
            </section>
        </article>
    <% end %>
<% end %> 

app/views/orders/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{@order.id}" %>

app/views/orders/edit.html.erb
<h1>Изменение заказа</h1>
<%= turbo_frame_tag @order.id do%>
    <article class="card mb-3">
        <section class="card-body">
            <%= render "form", url: edit_order_path(@order.id)%>
        </section>    
    </article>    
<% end %>    

app/views/orders/edit.turbo_stream.erb
<%= turbo_stream.update "#{order.id}", partial: "orders/edit", locals: { order: @order } %>

app/views/orders/index.html.erb
<%= render "filters", services: @services, executors: @executors, categories: @categories%>   

<div class="text-center"><h1>Заказы</h1></div>
<%= turbo_frame_tag "filter_orders" do%>
    <%= render "orders", orders: @orders %>
<% end %>

<div class="mb-3">
    <%= link_to "Добавить заказ", new_order_path, class: "btn btn-primary" %>
</div>

app/views/orders/index.turbo_stream.erb
<%= turbo_stream.update "filter_orders", partial: "orders/orders", locals: { orders: @orders } %>

app/views/orders/new.html.erb
<h1>Создание заказа</h1>
<%= render "form", url: new_order_path%>