config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :categories
  #resources :orders
  get "/orders", to: "orders#index", as: "orders"
  post "/orders", to: "orders#index", as: "sort_orders"
  get "/orders/new", to: "orders#new", as: "new_order"
  post "/orders/new", to: "orders#create", as: "create_order"
  get "/orders/edit/:id", to: "orders#edit", as: "edit_order"
  patch "/orders/edit/:id", to: "orders#update", as: "update_order"
  post "/orders/:id", to: "orders#destroy", as: "destroy_order"
  
  resources :executors
  resources :services
  root "orders#index"
end

app/views/layouts/_nav.html.erb
<header class="p-3 bg-dark text-white mb-3">
    <div class="container">        
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            </ul>
            <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
                    <li> <%= link_to "Заказы", orders_path, class: "nav-link px-2"%></li>
                    <li> <%= link_to "Услуги", services_path, class: "nav-link px-2"%></li>
                    <li> <%= link_to "Категории", categories_path, class: "nav-link px-2"%></li>
                    <li> <%= link_to "Исполнители", executors_path, class: "nav-link px-2"%></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render partial: "layouts/nav"%>
    <div class="container">
      <% flash.each do |k, v|%>
        <%= tag.div v, class: "alert alert-#{k} mt-3", role: "alert"%>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>